/** Default Material Symbol per taxonomy category slug (subcategory cards on category pages). */
const ICON_BY_CATEGORY: Record<string, string> = {
  arrangement: 'celebration',
  'avfall-og-bortkjoring': 'recycling',
  barnevakt: 'child_care',
  bilpleie: 'local_car_wash',
  'bilverksted-og-mekaniker': 'garage',
  boligstyling: 'chair',
  bryllup: 'favorite',
  design: 'palette',
  dyrepass: 'pets',
  eldreomsorg: 'volunteer_activism',
  elektriker: 'bolt',
  eventutleie: 'event',
  'flytting-og-transport': 'local_shipping',
  fotografi: 'photo_camera',
  frisor: 'content_cut',
  'hage-og-landskap': 'park',
  handverker: 'construction',
  'helse-og-velvare': 'spa',
  'it-hjelp': 'computer',
  'juridisk-radgivning': 'gavel',
  kampsport: 'sports_martial_arts',
  lasesmed: 'lock',
  'maler-og-tapetsering': 'format_paint',
  'mat-og-catering': 'restaurant',
  musikk: 'music_note',
  musikkundervisning: 'piano',
  'personlig-trener': 'fitness_center',
  regnskap: 'account_balance',
  renhold: 'cleaning_services',
  'rorlegger-og-vvs': 'plumbing',
  skadedyrkontroll: 'pest_control',
  smareparasjoner: 'handyman',
  snekker: 'carpenter',
  stylist: 'brush',
  sykkelreparasjon: 'pedal_bike',
  'som-og-skredder': 'checkroom',
  'tak-og-tekking': 'home_work',
  underholdning: 'stars',
  'undervisning-og-kurs': 'school',
  vaktmestertjenester: 'home_repair_service',
}

export function getCategoryMaterialIcon(categorySlug: string): string {
  return ICON_BY_CATEGORY[categorySlug] ?? 'category'
}
