/** Default Material Symbol per taxonomy category slug (subcategory cards on category pages). */
const ICON_BY_CATEGORY: Record<string, string> = {
  arrangement: 'celebration',
  barnevakt: 'child_care',
  behandling: 'spa',
  'bilverksted-og-mekaniker': 'garage',
  boligstyling: 'chair',
  bryllup: 'favorite',
  design: 'palette',
  dyrepass: 'pets',
  eldreomsorg: 'volunteer_activism',
  elektriker: 'bolt',
  eventutleie: 'event',
  flislegging: 'grid_on',
  flyttehjelp: 'local_shipping',
  fotografi: 'photo_camera',
  frisor: 'content_cut',
  'hage-og-landskap': 'park',
  handverker: 'construction',
  helse: 'medical_services',
  'it-hjelp': 'computer',
  'juridisk-radgivning': 'gavel',
  kampsport: 'sports_martial_arts',
  kokk: 'restaurant',
  'kurs-og-opplaering': 'school',
  lasesmed: 'lock',
  'maler-og-tapetsering': 'format_paint',
  mat: 'restaurant_menu',
  musikk: 'music_note',
  musikkundervisning: 'piano',
  'personlig-trener': 'fitness_center',
  privatundervisning: 'menu_book',
  regnskap: 'account_balance',
  'rorlegger-og-vvs': 'plumbing',
  renhold: 'cleaning_services',
  smareparasjoner: 'handyman',
  sprak: 'translate',
  stylist: 'brush',
  'tak-og-tekking': 'home_work',
  'transport-og-bud': 'local_shipping',
  underholdning: 'stars',
}

export function getCategoryMaterialIcon(categorySlug: string): string {
  return ICON_BY_CATEGORY[categorySlug] ?? 'category'
}
